// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1g5uGIbRjjzFhhZBtfPvlQxBOIMllo2E',
    appId: '1:210145068608:web:8731b6086a1a6fb5c381a5',
    messagingSenderId: '210145068608',
    projectId: 'login-form-with-fire-base',
    authDomain: 'login-form-with-fire-base.firebaseapp.com',
    storageBucket: 'login-form-with-fire-base.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8o-8d3fcjbhDQOMA_b228LnShuUjvdRE',
    appId: '1:210145068608:android:d9a96c9d93a15661c381a5',
    messagingSenderId: '210145068608',
    projectId: 'login-form-with-fire-base',
    storageBucket: 'login-form-with-fire-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMX8xsrxPprWUr3_neJkwFOtRn21Sa0cQ',
    appId: '1:210145068608:ios:a9608d0f68e1939fc381a5',
    messagingSenderId: '210145068608',
    projectId: 'login-form-with-fire-base',
    storageBucket: 'login-form-with-fire-base.appspot.com',
    iosBundleId: 'com.example.formWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMX8xsrxPprWUr3_neJkwFOtRn21Sa0cQ',
    appId: '1:210145068608:ios:8614a005d3049479c381a5',
    messagingSenderId: '210145068608',
    projectId: 'login-form-with-fire-base',
    storageBucket: 'login-form-with-fire-base.appspot.com',
    iosBundleId: 'com.example.formWithFirebase.RunnerTests',
  );
}
